platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: latest

inputs:
- name: git-docker-boshrelease
- name: git-docker-ce-release

params:
  GCS_JSON_KEY:

run:
  path: ./git-docker-boshrelease/ci/scripts/update-docker

outputs:
- name: git-docker-boshrelease-output
